In [1]:
import numpy as np
import matplotlib.pyplot as plt

Problem 1

In [2]:
X = np.array([[3, 2, 1],[2, 4, 5],[1, 2, 3],[0, 2, 5]])
print(X)
# sample mean
xm = np.mean(X,axis=0)
print(xm)

[[3 2 1]
 [2 4 5]
 [1 2 3]
 [0 2 5]]
[1.5 2.5 3.5]


In [3]:
# covariance matrix
Xm = X - xm[None,:]
print(Xm)
Q = (1/X.shape[0])*Xm.T.dot(Xm)
print(Q)

[[ 1.5 -0.5 -2.5]
 [ 0.5  1.5  1.5]
 [-0.5 -0.5 -0.5]
 [-1.5 -0.5  1.5]]
[[ 1.25  0.25 -1.25]
 [ 0.25  0.75  0.75]
 [-1.25  0.75  2.75]]


In [4]:
e_values, e_vectors = np.linalg.eig(Q)
print(e_values)
print(e_vectors)

[3.56166464 1.1733803  0.01495506]
[[-0.45056922 -0.66677184 -0.59363515]
 [ 0.19247228 -0.72187235  0.66472154]
 [ 0.87174641 -0.18524476 -0.45358856]]


In [5]:
Z = Xm.dot(e_vectors)
print(Z)

[[-2.95145599 -0.17610969 -0.0888421 ]
 [ 1.37104342 -1.69406159  0.0198819 ]
 [-0.30682473  0.78694448  0.19125108]
 [ 1.8872373   1.0832268  -0.12229089]]


In [10]:
Xhat = xm + Z.dot(e_vectors.T)
print(Xhat)

[[3.0000000e+00 2.0000000e+00 1.0000000e+00]
 [2.0000000e+00 4.0000000e+00 5.0000000e+00]
 [1.0000000e+00 2.0000000e+00 3.0000000e+00]
 [8.8817842e-16 2.0000000e+00 5.0000000e+00]]


In [11]:
err = np.sum(np.sum((X-Xhat)**2, axis=1), axis=0)*(1/X.shape[0])
print(err)

1.4791141972893971e-30


In [12]:
# the first two columns are the eigenvectors corresponding to the two highest eigenvalues
two_pc = e_vectors[:,:2]
Z2 = Xm.dot(two_pc)
print(Z2)

[[-2.95145599 -0.17610969]
 [ 1.37104342 -1.69406159]
 [-0.30682473  0.78694448]
 [ 1.8872373   1.0832268 ]]


In [15]:
Xhat2 = xm + Z2.dot(two_pc.T)
print(Xhat2)

[[ 2.94726021  2.05905526  0.95970224]
 [ 2.0118026   3.98678407  5.0090182 ]
 [ 1.11353336  1.87287129  3.0867493 ]
 [-0.07259617  2.08128939  4.94453025]]


In [16]:
err2 = np.sum(np.sum((X-Xhat2)**2, axis=1), axis=0)
print(err2)

0.059820245731225935


In [17]:
skipped = Xm.dot(e_vectors[:,2])
err = np.sum(skipped**2)
print(err)

0.05982024573122597


The sum of reconstruction error squares equals the sum of squares of skipped PCA coefficients.

In [19]:
print(err2*(1/X.shape[0]))
print(e_values[2])

0.014955061432806484
0.014955061432806133


The mean error is equal to the eigenvalue associated to the skipped eigenvector

Problem 2

In [20]:
u = np.array([1,0,2])
v1 = np.array([1,1,0])*(1/np.sqrt(2))
v2 = np.array([1,-1,0])*(1/np.sqrt(2))
x = np.array([2,3,4])
b = np.hstack((v1[:,None],v2[:,None]))

In [21]:
y = (x-u).dot(b)
print(y)

[ 2.82842712 -1.41421356]


In [22]:
xhat = u + y.dot(b.T)
print(xhat)

[2. 3. 2.]


In [23]:
print(np.sum((x-xhat)**2))

4.0
